name: Render Books

on: push

jobs:
  render:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: true
      max-parallel: 10
      matrix:
        book: [1-fundamentals]
        format: [pdf, epub]
    steps:
      - uses: actions/checkout@v2

      - name: create book file list
        id: files_list
        env:
          BOOK: ${{ matrix.book }}
        run: |
          mkdir output
          echo "::set-output name=files::$(printf '"%s" ' src/books/${BOOK}/**/*.md)"

      - name: render book
        uses: docker://pandoc/latex:2.9
        with:
          args: --from gfm --output=output/${{ matrix.book }}.${{ matrix.format }} ${{ steps.files_list.outputs.files }}

      - name: upload artifact
        uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.book }}-${{ matrix.format }}
          path: output/${{ matrix.book }}.${{ matrix.format }}
