name: Render Books

on: push

jobs:
  render:
    runs-on: ubuntu-22.04
    container: pandoc/latex:2.9
    strategy:
      max-parallel: 5
      matrix:
        book: [1-fundamentals]
        format: [pdf, epub]
    steps:
      - uses: actions/checkout@v2

      - name: create book file list
        id: files_list
        working-directory: src/books/${{ matrix.book }}
        run: |
          echo "$(pwd)"
          printf '"%s" ' **/*.md
          echo "::set-output name=files::$(printf '"%s" ' **/*.md)"

      - name: render book
        env:
          BOOK: ${{ matrix.book }}
          FORMAT: ${{ matrix.format }}
          FILES: ${{ steps.files_list.outputs.files }}
        working-directory: src/books/${{ matrix.book }}
        run: |
          pandoc \
            --from gfm+emoji -t \
            --metadata-file metadata.yaml \
            --template ../../meta/template.tex \
            --indented-code-classes=javascript \
            --to ${{ matrix.format }} \
            --toc --toc-depth 2 \
            --output=output ${{ steps.files_list.outputs.files }}
          ls -la

      - name: upload artifact
        uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.book }}-${{ matrix.format }}
          path: src/books/${{ matrix.book }}/output
